name: OpenAI API Test

on: [push, pull_request]

jobs:
  run-openai-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Debug Environment Variables
        run: echo "API Key: ${{ secrets.OPENAI_API_KEY }}"
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Run the script
        run: python app.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
